version: "3"

services:
  webapp:
    build:
      context: ./webapp
    volumes:
      - ./webapp:/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3001
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - 3001:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - DB_NAME=ebay_alert_db
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_SECURE=false
      - EBAY_TOKEN=v^1.1#i^1#I^3#r^0#p^1#f^0#t^H4sIAAAAAAAAAOVYb2wTZRjftd3GxPknThBitN6YEshd37v2uvZGq2VjWQXWSifBETLe3r23HbveNXdXti4oS02K4Af/JKIZflj8NzSiElC/+gGFYExEMWAQ98k/oAEkxpkIwfeuZXSTsMkqLLFfmnve533e3+95fs/73r1gsKpmSb4tP1ZLVDuGB8GggyCYuaCmqnLpbU7HwsoKUOJADA8uGnTlnD8vM2BKSfNrkJHWVAO5+1OKavC2MURmdJXXoCEbvApTyOBNgU9EVq/iWRrwaV0zNUFTSHe0JUQiETQCCLzQ5/f7oNCIrerlmB1aiOQYNigxLMdISRYG/QCPG0YGRVXDhKoZIlnABCkQoJhABwt4r4/3cTTHNnaS7rVIN2RNxS40IMM2XN6eq5dgvTZUaBhIN3EQMhyNtCZikWjLivaOZZ6SWOFiHhImNDPGxKdmTUTutVDJoGsvY9jefCIjCMgwSE+4sMLEoHzkMpjrgG+nWuIYJLF+0d/IiUmvny1LKls1PQXNa+OwLLJISbYrj1RTNrNTZRRnI7kJCWbxqR2HiLa4rb/HMlCRJRnpIXLF8sgTkXicDLfIqFuLKTIFFcyYiq9pobw+X8AbZBsRJaJAMunlpOIqhVDFHE9apllTRdnKmOFu18zlCENGkxPDliQGO8XUmB6RTAtOqR87nkC206pooYQZs0e1iopSOAtu+3Hq9I/PNk1dTmZMNB5h8oCdnxAJ02lZJCcP2kIsaqffCJE9ppnmPZ6+vj66z0trereHBYDxrFu9KiH0oBQkC75Wr2N/eeoJlGxTERCeaci8mU1jLP1YqBiA2k2GvcEgCHDFvE+EFZ5s/YehhLNnYjuUqz38QYkVhCBgvEEGMEAqR3uEiwr1WDhQEmapFNR7kZlWoIAoAessk0K6LPJYnqw3IGGxYhiULyhJVJIT/RQjIQQQSiaFYOB/0yXT1XlC0NIorimykC2X2sukdF2MQ93MJpCiYMN0JX9VkoZF8gbRs3p9mhStGAYOAtMybQmbFrSUR4N4R7NMXTbqGfGOpNPRVCpjwqSComXbzW7GTnZVejI+6GcVJ1y/QiFlsXBC03Y1aWOzQOvI0DI6fjmhY9aZ1aH1IhVvAqauKXgnWcvMuNCzrL7/ZqO8PtJlPaKvi7TV6/+FsAVFxvrpusnsbkJJZWjOLsoM5/czfuCbYUGb7YJ2ZG/YKTRNem2aYSJxZtSwFGYXKUuXl2XJSd4AhSTOjy1+hoIBMUD5GN+0j9UrBhcz5Tu0Z+LnfLjC/jE54kOQI/Y6CAJ4QANTDx6ocj7uct660JBNRMtQog25W8VfqTqie1E2DWXdUUXIL3617ZuSC4ThDeCe8SuEGiczt+Q+Adx7ZaSSuX1+LYO3ICbAAtyeXCeovzLqYua56pb8/kHy8O5HXV0a0cWmhhd/Jh2OgtpxJ4KorHDliIqVTf2vE+tu0Q7N3RY6ORRgN626WLnz5NH6u/7YQY/UHfiopvPShbNbzsef2vPOgt2b8q137Ms1v0x/2nRm6577Tpx/ITjSED61YOfGpb82P3Pbaz3nqs9XtB4/PjrWcezMx4vzX39//w/zW3fsb6CPQPerB7/95M6h0w/99u4XjQP5c49sePOvnc8dv5D/nF568btLu06NBQ62nebO9LaOHdm4fnGuvS1nzpm/960/V9aNDThf2rdmaCS2pbrumPHT89uPbZRq5XyTY7Rn89nOkdMnHJkvyYed8cTboxp3N791b+z9N44ePrToSe3poYGh5nqPr2nJdkfDe8vmrN81Oi/k218vHHi2euCX6ld+fLBQvr8B8ztaudoRAAA=
  mongo:
    image: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025