version: "3"

services:
  server:
    build:
      context: './server'
    volumes:
      - "./server:/app"
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/
  mongo:
    image: mongo